var MINUS_INFINITE = -100000;
var PLUS_INFINITE = 100000;

var WEIGHT_VOWEL = 20;
var WEIGHT_NEAR_VOWEL = 20;
var WEIGHT_BORDER = [3,2,1,2,3,
                     2,2,0,2,2,
                     1,0,0,0,1,
                     2,2,0,2,2,
                     3,2,1,2,3];

var WEIGHT_DEEP_RED = -5;
var WEIGHT_DEEP_BLUE = 5;
var WEIGHT_RED = -1;
var WEIGHT_BLUE = 1;

var MAX_MOVES_EXPLORE = 10000;

exports.WEIGHT_VOWEL = WEIGHT_VOWEL;
exports.WEIGHT_NEAR_VOWEL = WEIGHT_NEAR_VOWEL;
exports.WEIGHT_BORDER = WEIGHT_BORDER;

exports.MINUS_INFINITE = MINUS_INFINITE;
exports.PLUS_INFINITE = PLUS_INFINITE;

exports.WEIGHT_DEEP_RED = WEIGHT_DEEP_RED;
exports.WEIGHT_DEEP_BLUE = WEIGHT_DEEP_BLUE ;
exports.WEIGHT_RED = WEIGHT_RED ;
exports.WEIGHT_BLUE = WEIGHT_BLUE ;

exports.MAX_MOVES_EXPLORE = MAX_MOVES_EXPLORE;
